function COM = COM_gymnast(in1,in2)
%COM_gymnast
%    COM = COM_gymnast(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Dec-2022 17:44:19

com_legs = in2(6,:);
com_torso = in2(5,:);
dth_1 = in1(4,:);
dth_2 = in1(5,:);
dth_3 = in1(6,:);
l_arms = in2(1,:);
l_torso = in2(2,:);
m_arms = in2(7,:);
m_legs = in2(9,:);
m_torso = in2(8,:);
th_1 = in1(1,:);
th_2 = in1(2,:);
th_3 = in1(3,:);
t2 = cos(th_1);
t3 = sin(th_1);
t4 = th_1+th_2;
t6 = m_arms+m_legs+m_torso;
t5 = l_arms.*t2;
t7 = cos(t4);
t8 = l_arms.*t3;
t9 = sin(t4);
t10 = t4+th_3;
t11 = com_torso.*m_arms.*t2;
t12 = com_torso.*m_arms.*t3;
t19 = 1.0./t6;
t13 = cos(t10);
t14 = sin(t10);
t15 = com_torso.*t7;
t16 = l_torso.*t7;
t17 = com_torso.*t9;
t18 = l_torso.*t9;
t20 = com_legs.*t13;
t21 = com_legs.*t14;
t22 = t5+t15;
t23 = t8+t17;
t24 = m_torso.*t22;
t25 = m_torso.*t23;
t26 = t5+t16+t20;
t27 = t8+t18+t21;
t28 = m_legs.*t26;
t29 = m_legs.*t27;
t30 = t12+t25+t29;
t31 = t11+t24+t28;
COM = [t19.*t30;-t19.*t31;dth_1.*t19.*t31+dth_2.*t19.*(m_legs.*(t16+t20)+m_torso.*t15)+dth_3.*m_legs.*t19.*t20;dth_1.*t19.*t30+dth_2.*t19.*(m_legs.*(t18+t21)+m_torso.*t17)+dth_3.*m_legs.*t19.*t21];
