function V = energy_Potential_gymnast(in1,in2)
%energy_Potential_gymnast
%    V = energy_Potential_gymnast(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Dec-2022 17:44:20

com_legs = in2(6,:);
com_torso = in2(5,:);
g = in2(13,:);
l_arms = in2(1,:);
l_torso = in2(2,:);
m_arms = in2(7,:);
m_legs = in2(9,:);
m_torso = in2(8,:);
th_1 = in1(1,:);
th_2 = in1(2,:);
th_3 = in1(3,:);
t2 = cos(th_1);
t3 = th_1+th_2;
t4 = l_arms.*t2;
t5 = cos(t3);
V = -g.*m_torso.*(t4+com_torso.*t5)-g.*m_legs.*(t4+l_torso.*t5+com_legs.*cos(t3+th_3))-com_torso.*g.*m_arms.*t2;
