function T = energy_Kinetic_gymnast(in1,in2)
%energy_Kinetic_gymnast
%    T = energy_Kinetic_gymnast(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Dec-2022 17:44:20

I_arms = in2(10,:);
I_legs = in2(12,:);
I_torso = in2(11,:);
com_legs = in2(6,:);
com_torso = in2(5,:);
dth_1 = in1(4,:);
dth_2 = in1(5,:);
dth_3 = in1(6,:);
l_arms = in2(1,:);
l_torso = in2(2,:);
m_arms = in2(7,:);
m_legs = in2(9,:);
m_torso = in2(8,:);
th_1 = in1(1,:);
th_2 = in1(2,:);
th_3 = in1(3,:);
t2 = cos(th_1);
t3 = sin(th_1);
t4 = th_1+th_2;
t5 = com_torso.^2;
t6 = dth_1.^2;
t7 = l_arms.*t2;
t8 = cos(t4);
t9 = l_arms.*t3;
t10 = sin(t4);
t11 = t4+th_3;
t12 = cos(t11);
t13 = sin(t11);
t14 = l_torso.*t8;
t15 = l_torso.*t10;
t16 = com_legs.*t12;
t17 = com_legs.*t13;
T = (I_arms.*t6)./2.0+(m_legs.*((dth_2.*(t14+t16)+dth_3.*t16+dth_1.*(t7+t14+t16)).^2+(dth_2.*(t15+t17)+dth_3.*t17+dth_1.*(t9+t15+t17)).^2))./2.0+(I_torso.*(dth_1+dth_2).^2)./2.0+(m_arms.*(t2.^2.*t5.*t6+t3.^2.*t5.*t6))./2.0+(m_torso.*((dth_1.*(t7+com_torso.*t8)+com_torso.*dth_2.*t8).^2+(dth_1.*(t9+com_torso.*t10)+com_torso.*dth_2.*t10).^2))./2.0+(I_legs.*(dth_1+dth_2+dth_3).^2)./2.0;
