function keypoints = keypoints_gymnast(in1,in2)
%KEYPOINTS_GYMNAST
%    KEYPOINTS = KEYPOINTS_GYMNAST(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Dec-2022 17:44:19

l_arms = in2(1,:);
l_legs = in2(3,:);
l_torso = in2(2,:);
th_1 = in1(1,:);
th_2 = in1(2,:);
th_3 = in1(3,:);
t2 = cos(th_1);
t3 = sin(th_1);
t4 = th_1+th_2;
t5 = l_arms.*t2;
t6 = cos(t4);
t7 = l_arms.*t3;
t8 = sin(t4);
t9 = t4+th_3;
t10 = cos(t9);
t11 = sin(t9);
t12 = l_torso.*t6;
t13 = l_torso.*t8;
t14 = -t5;
t15 = l_legs.*t10;
t16 = l_legs.*t11;
t17 = -t12;
t18 = -t15;
keypoints = reshape([t7,t14,0.0,t7+t13,t14+t17,0.0,t7+t13+t16,t14+t17+t18,0.0,t7-t13./2.0,t12./2.0+t14,0.0,t7+t13+t15./5.0+t16,t14+t16./5.0+t17+t18,0.0],[3,5]);
